import { Component } from '@angular/core';

interface Item {
  name: string;
  zone: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  items: Item[] = [
    { name: 'Abbotsford', zone: 'Zone 6' },
{ name: 'Bentleigh East', zone: 'Zone 10' },
{ name: 'Cairnlea', zone: 'Zone 1' },
{ name: 'Cranbourne Sth', zone: 'DDY 3' },
{ name: 'Aberfeldie', zone: 'Zone 5' },
{ name: 'Berwick', zone: 'NWN' },
{ name: 'Calder Park', zone: 'Zone 3' },
{ name: 'Cranbourne W', zone: 'DDY 3' },
{ name: 'Airport West', zone: 'Zone 5' },
{ name: 'Bittern', zone: 'DDY 4' },
{ name: 'Camberwell', zone: 'Zone 7' },
{ name: 'Cremorne', zone: 'Zone 9' },
{ name: 'Albanvale', zone: 'Zone 1' },
{ name: 'Black Rock', zone: 'DDY 6' },
{ name: 'Campbelfield', zone: 'Zone 8' },
{ name: 'Crib Point', zone: 'DDY 4' },
{ name: 'Albert Park', zone: 'Zone 9' },
{ name: 'Blackburn', zone: 'DDY 2' },
{ name: 'Canterbury', zone: 'Zone 7' },
{ name: 'COIMADAI', zone: 'Zone 3B' },
{ name: 'Albion', zone: 'Zone 1' },
{ name: 'Blackburn North', zone: 'DDY 2' },
{ name: 'Cape Schank', zone: 'DDY 4' },
{ name: 'Croydon', zone: 'DDY 1' },
{ name: 'Alphington', zone: 'Zone 7' },
{ name: 'Blackburn South', zone: 'DDY 2' },
{ name: 'Carlton', zone: 'Zone 8' },
{ name: 'Croydon Hills', zone: 'DDY 1' },
{ name: 'Altona', zone: 'Zone 2' },
{ name: 'Blairgowrie', zone: 'DDY 4' },
{ name: 'Carlton North', zone: 'Zone 8' },
{ name: 'Croydon North', zone: 'DDY 1' },
{ name: 'Altona Meadow', zone: 'Zone 2' },
{ name: 'Bonbeach', zone: 'DDY 6' },
{ name: 'Carnegie', zone: 'Zone 8' },
{ name: 'Croydon South', zone: 'DDY 1' },
{ name: 'Altona North', zone: 'Zone 2' },
{ name: 'Boneo', zone: 'DDY 4' },
{ name: 'Caroline Springs', zone: 'Zone 3' },
{ name: 'Dallas', zone: 'Zone 8' },
{ name: 'Aspendale', zone: 'DDY 6' },
{ name: 'Boronia', zone: 'DDY 1' },
{ name: 'Carrum', zone: 'DDY 6' },
{ name: 'Dandenong', zone: 'DDY 5' },
{ name: 'Ardeer', zone: 'Zone 1' },
{ name: 'Box Hill', zone: 'DDY 2' },
{ name: 'Carrum Downs', zone: 'DDY 4' },
{ name: 'Dandenong Nth', zone: 'DDY 5' },
{ name: 'Armadale', zone: 'Zone 6' },
{ name: 'Box Hill North', zone: 'DDY 2' },
{ name: 'Caulfield', zone: 'Zone 10' },
{ name: 'Dandenong Sth', zone: 'DDY 5' },
{ name: 'Arthurs Seat', zone: 'DDY 4' },
{ name: 'Box Hill South', zone: 'DDY 2' },
{ name: 'Caulfield East', zone: 'Zone 10' },
{ name: 'Darley', zone: 'Zone 3B' },
{ name: 'Ascot Vale', zone: 'Zone 5' },
{ name: 'Braeside', zone: 'DDY 5' },
{ name: 'Caulfield North', zone: 'Zone 10' },
{ name: 'Deer Park', zone: 'Zone 1' },
{ name: 'Ashburton', zone: 'DDY 2' },
{ name: 'Braybrook', zone: 'Zone 1' },
{ name: 'Caulfield South', zone: 'Zone 10' },
{ name: 'Delahey', zone: 'Zone 3' },
{ name: 'Ashwood', zone: 'DDY 2' },
{ name: 'Briar Hill', zone: 'Zone 5' },
{ name: 'Chadstone', zone: 'Zone 6' },
{ name: 'Derrimut', zone: 'Zone 1' },
{ name: 'Aspendale Gdns', zone: 'DDY 6' },
{ name: 'Brighton', zone: 'Zone 10' },
{ name: 'Chadstone S/C', zone: 'Zone 6' },
{ name: 'Devon Meadows', zone: 'DDY 2' },
{ name: 'Attwood', zone: 'Zone 3' },
{ name: 'Brighton East', zone: 'Zone 10' },
{ name: 'Chelsea', zone: 'DDY 6' },
{ name: 'Diggers Rest', zone: 'Zone 3B' },
{ name: 'Avondale Hts', zone: 'Zone 2' },
{ name: 'Brighton North', zone: 'Zone 10' },
{ name: 'Chelsea Heights', zone: 'DDY 6' },
{ name: 'Dingley Village', zone: 'DDY 5' },
{ name: 'Bacchus Marsh', zone: 'Zone 3B' },
{ name: 'Broadmeadows', zone: 'Zone 8' },
{ name: 'Cheltenham', zone: 'DDY 6' },
{ name: 'Docklands', zone: 'Zone 8' },
{ name: 'Balaclava', zone: 'Zone 10' },
{ name: 'Brookfield', zone: 'Zone 1' },
{ name: 'Chirnside Park', zone: 'DDY 1' },
{ name: 'Doncaster', zone: 'DDY 2' },
{ name: 'Balnarring', zone: 'DDY 4' },
{ name: 'Brooklyn', zone: 'Zone 2' },
{ name: 'Clarinda', zone: 'DDY 5' },
{ name: 'Doncaster East', zone: 'DDY 2' },
{ name: 'Balnarring Beach', zone: 'DDY 4' },
{ name: 'Brunswick', zone: 'Zone 5' },
{ name: 'Clayton', zone: 'DDY 5' },
{ name: 'Donvale', zone: 'DDY 1' },
{ name: 'Balwyn', zone: 'Zone 7' },
{ name: 'Brunswick East', zone: 'Zone 5' },
{ name: 'Clayton South', zone: 'DDY 5' },
{ name: 'Doveton', zone: 'DDY 3' },
{ name: 'Balwyn North', zone: 'Zone 7' },
{ name: 'Brunswick West', zone: 'Zone 5' },
{ name: 'Clifton Hill', zone: 'Zone 6' },
{ name: 'Dromana', zone: 'DDY 4' },
{ name: 'Bangholme', zone: 'DDY 5' },
{ name: 'Bulla', zone: 'ONF' },
{ name: 'Coburg', zone: 'Zone 5' },
{ name: 'Eaglemont', zone: 'Zone 6' },
{ name: 'Baxter', zone: 'DDY 2' },
{ name: 'Bulleen', zone: 'Zone 7' },
{ name: 'Coburg North', zone: 'Zone 5' },
{ name: 'East Melbourne', zone: 'Zone 9' },
{ name: 'Bayswater', zone: 'DDY 1' },
{ name: 'Bundoora', zone: 'Zone 4' },
{ name: 'Collingwood', zone: 'Zone 6' },
{ name: 'Edithvale', zone: 'DDY 6' },
{ name: 'Bayswater North', zone: 'DDY 1' },
{ name: 'Burnley', zone: 'Zone 9' },
{ name: 'Coolaroo', zone: 'Zone 8' },
{ name: 'Elsternwick', zone: 'Zone 10' },
{ name: 'Beaconsfield', zone: 'NWN' },
{ name: 'Burnside', zone: 'Zone 1' },
{ name: 'Craigieburn', zone: 'Zone 3' },
{ name: 'Eltham', zone: 'Zone 5' },
{ name: 'Beaumaris', zone: 'DDY 6' },
{ name: 'Burnside Heights', zone: 'Zone 1' },
{ name: 'Cranbourne', zone: 'DDY 3' },
{ name: 'Eltham North', zone: 'Zone 5' },
{ name: 'Bellfield', zone: 'Zone 6' },
{ name: 'Burwood', zone: 'DDY 2' },
{ name: 'Cranbourne East', zone: 'DDY 3' },
{ name: 'Elwood', zone: 'Zone 10' },
{ name: 'Bentleigh', zone: 'Zone 10' },
{ name: 'Essendon', zone: 'Zone 5' },
{ name: 'Essendon North', zone: 'Zone 5' },
{ name: 'Essendon West', zone: 'Zone 5' },
{ name: 'Eumemmerring', zone: 'DDY 3' },
{ name: 'Fairfield', zone: 'Zone 7' },
{ name: 'Fawkner', zone: 'Zone 4' },
{ name: 'Ferntree Gully', zone: 'DDY 1' },
{ name: 'Fingal', zone: 'DDY 4' },
{ name: 'Fitzroy', zone: 'Zone 6' },
{ name: 'Fitzroy North', zone: 'Zone 5' },
{ name: 'Flemington', zone: 'Zone 9' },
{ name: 'Flinders', zone: 'DDY 4' },
{ name: 'Flinders naval', zone: 'DDY 4' },
{ name: 'Footscray', zone: 'Zone 2' },
{ name: 'Forest Hill', zone: 'DDY 2' },
{ name: 'Frankston CBD', zone: 'DDY 4' },
{ name: 'Frankston North', zone: 'DDY 4' },
{ name: 'Frankston S/C', zone: 'DDY 4' },
{ name: 'Frankston South', zone: 'DDY 4' },
{ name: 'Gardenvale', zone: 'Zone 10' },
{ name: 'Gisborne', zone: 'Zone 3B' },
{ name: 'Gladstone Park', zone: 'Zone 8' },
{ name: 'Glen Iris', zone: 'DDY 2' },
{ name: 'Glen Waverley', zone: 'DDY 2' },
{ name: 'Glenhuntly', zone: 'Zone 10' },
{ name: 'Glenroy', zone: 'Zone 5' },
{ name: 'Gowanbrae', zone: 'Zone 8' },
{ name: 'Greensborough', zone: 'Zone 5' },
{ name: 'Greenvale', zone: 'Zone 3' },
{ name: 'Hallam', zone: 'DDY 3' },
{ name: 'Hampton', zone: 'Zone 10' },
{ name: 'Hampton East', zone: 'Zone 10' },
{ name: 'Hampton Park', zone: 'NWN' },
{ name: 'Hastings', zone: 'DDY 4' },
{ name: 'Burwood East', zone: 'DDY 2' },
{ name: 'Hadfield', zone: 'Zone 5' },
{ name: 'Heidelberg', zone: 'Zone 5' },
{ name: 'Heidelberg Hts', zone: 'Zone 5' },
{ name: 'Heidelberg W', zone: 'Zone 5' },
{ name: 'Hetherton', zone: 'DDY 4' },
{ name: 'Highett', zone: 'Zone 10' },
{ name: 'Highpoint S/C', zone: 'Zone 2' },
{ name: 'Hillside', zone: 'Zone 3' },
{ name: 'HMAS Cerberus', zone: 'DDY 4' },
{ name: 'Hoppers Xing', zone: 'Zone 2' },
{ name: 'hoptoun park', zone: 'Zone 38' },
{ name: 'Hughesdale', zone: 'DDY 5' },
{ name: 'Huntingdale', zone: 'DDY 5' },
{ name: 'Ivanhoe', zone: 'Zone 6' },
{ name: 'Ivanhoe East', zone: 'Zone 6' },
{ name: 'Jacana', zone: 'Zone 5' },
{ name: 'Kealba', zone: 'Zone 1' },
{ name: 'Keilor', zone: 'Zone 1' },
{ name: 'Keilor Downs', zone: 'Zone 3' },
{ name: 'Keilor East', zone: 'Zone 2' },
{ name: 'Keilor North', zone: 'Zone 3' },
{ name: 'Keilor Park', zone: 'Zone 8' },
{ name: 'Kensington', zone: 'Zone 9' },
{ name: 'Kew', zone: 'Zone 7' },
{ name: 'Kew East', zone: 'Zone 7' },
{ name: 'Keysborough', zone: 'DDY 5' },
{ name: 'Kilsyth', zone: 'DDY 1' },
{ name: 'Kilsyth South', zone: 'DDY 1' },
{ name: 'Kings Park', zone: 'Zone 3' },
{ name: 'Kingsbury', zone: 'Zone 4' },
{ name: 'Kingsville', zone: 'Zone 2' },
{ name: 'Kingsville west', zone: 'Zone 2' },
{ name: 'Knox City S/C', zone: 'DDY 1' },
{ name: 'Knoxfield', zone: 'DDY 1' },
{ name: 'Cranbourne Nth', zone: 'DDY 3' },
{ name: 'Lalor', zone: 'Zone 4' },
{ name: 'Langwarrin', zone: 'DDY 4' },
{ name: 'Lanwarrin South', zone: 'DDY 4' },
{ name: 'Latrobe Uni', zone: 'Zone 4' },
{ name: 'Laverton', zone: 'Zone 2' },
{ name: 'Laverton North', zone: 'Zone 1' },
{ name: 'Laverton RAAF', zone: 'Zone 2' },
{ name: 'Lilydale', zone: 'DDY 1' },
{ name: 'long forest', zone: 'Zone 3B' },
{ name: 'Lower Plenty', zone: 'Zone 5' },
{ name: 'Lynbrook', zone: 'NWN' },
{ name: 'Lysterfield', zone: 'DDY 1' },
{ name: 'Macleod', zone: 'Zone 5' },
{ name: 'Maddingley', zone: 'Zone 3B' },
{ name: 'Maidstone', zone: 'Zone 2' },
{ name: 'Mainridge', zone: 'DDY 4A' },
{ name: 'Malvern', zone: 'Zone 6' },
{ name: 'Malvern East', zone: 'ZONE 6' },
{ name: 'Maribynong', zone: 'Zone 2' },
{ name: 'McCrae', zone: 'DDY 4' },
{ name: 'McKinnon', zone: 'Zone 10' },
{ name: 'Meadow Heights', zone: 'Zone 3' },
{ name: 'Melbourne Airport', zone: 'Zone 8' },
{ name: 'Melbourne CBD', zone: '1 Zone 8' },
{ name: 'Melton', zone: 'Zone 1' },
{ name: 'Melton South', zone: 'Zone 1' },
{ name: 'Melton West', zone: 'Zone 1' },
{ name: 'Merricks', zone: 'DDY 4' },
{ name: 'Merricks Beach', zone: 'DDY 4' },
{ name: 'Merricks North', zone: 'DDY 4' },
{ name: 'Merrimu', zone: 'Zone 3B' },
{ name: 'Mentone', zone: 'DDY 6' },
{ name: 'Middle Park', zone: 'Zone 9' },
{ name: 'Mill Park', zone: 'Zone 4' },
{ name: 'Endeavour Hills', zone: 'DDY 3' },
{ name: 'Epping', zone: 'Zone 4' },
{ name: 'Mont Albert North', zone: 'DDY 2' },
{ name: 'montmorency', zone: 'Zone 5' },
{ name: 'Moonee Ponds', zone: 'Zone 9' },
{ name: 'Moorabbin', zone: 'Zone 10' },
{ name: 'Moorabbin Airport', zone: 'DDY 6' },
{ name: 'moorabbin east', zone: 'DDY 6' },
{ name: 'Moorooduc', zone: 'DDY 4' },
{ name: 'Mooroolbark', zone: 'DDY 1' },
{ name: 'Mordialloc', zone: 'DDY 6' },
{ name: 'Moreland', zone: 'Zone 4' },
{ name: 'Mornington', zone: 'DDY 4' },
{ name: 'Mount Eliza', zone: 'DDY 4' },
{ name: 'Mount Martha', zone: 'DDY 4' },
{ name: 'Mount Waverley', zone: 'DDY 2' },
{ name: 'Mulgrave', zone: 'DDY 5' },
{ name: 'Murrumbeena', zone: 'Zone 10' },
{ name: 'Narre Warren', zone: 'DDY 3' },
{ name: 'Narre Warren South', zone: 'NWN' },
{ name: 'Newport', zone: 'Zone 2' },
{ name: 'Niddrie', zone: 'Zone 5' },
{ name: 'Noble Park', zone: 'DDY 5' },
{ name: 'Noble Park North', zone: 'DDY 5' },
{ name: 'North Melbourne', zone: 'Zone 9' },
{ name: 'Northcote', zone: 'zone 7' },
{ name: 'Notting Hill', zone: 'DDY2' },
{ name: 'Nunawading', zone: 'DDY 2' },
{ name: 'Oak Park', zone: 'Zone 5' },
{ name: 'Oakleigh', zone: 'DDY 5' },
{ name: 'Oakleigh East', zone: 'DDY 5' },
{ name: 'Oakleigh South', zone: 'DDY 5' },
{ name: 'Officer', zone: 'NWN' },
{ name: 'Ormond', zone: 'Zone 10' },
{ name: 'Pakenham', zone: 'NWN' },
{ name: 'Hawthorn', zone: 'Zone 7' },
{ name: 'Hawthorn East', zone: 'Zone 7' },
{ name: 'Heathmont', zone: 'DDY 1' },
{ name: 'Port Melbourne', zone: 'Zone 9' },
{ name: 'Portsea', zone: 'DDY 4' },
{ name: 'Prahran', zone: 'Zone 6' },
{ name: 'Preston', zone: 'Zone 4' },
{ name: 'Princes Hill', zone: 'Zone 8' },
{ name: 'Ravenhall', zone: 'Zone 1' },
{ name: 'Red Hill', zone: 'DDY 4' },
{ name: 'Red Hill South', zone: 'DDY 4' },
{ name: 'Reservoir', zone: 'Zone 4' },
{ name: 'Research', zone: 'Zone 5' },
{ name: 'cremorne', zone: 'Zone 9' },
{ name: 'Ringwood', zone: 'DDY 1' },
{ name: 'Ringwood East', zone: 'DDY 1' },
{ name: 'Ringwood North', zone: 'DDY 1' },
{ name: 'Ripponlea', zone: 'Zone 10' },
{ name: 'Rosanna', zone: 'Zone 5' },
{ name: 'Rosebud', zone: 'DDY 4' },
{ name: 'Rosebud West', zone: 'DDY 4' },
{ name: 'Rowville', zone: 'DDY 1' },
{ name: 'Roxburgh Park', zone: 'Zone 3' },
{ name: 'Royal Mel Hospita', zone: 'Zone 5' },
{ name: 'Rye', zone: 'DDY 4' },
{ name: 'Safety beach', zone: 'DDY 4' },
{ name: 'Saint Helena', zone: 'Zone 5' },
{ name: 'Sandhurst', zone: 'DDY 4' },
{ name: 'Sandringham', zone: 'Zone 10' },
{ name: 'Scoresby', zone: 'DDY 1' },
{ name: 'Seabrook', zone: 'Zone 2' },
{ name: 'Seaford', zone: 'DDY 6' },
{ name: 'Seaholme', zone: 'Zone 2' },
{ name: 'Seddon', zone: 'Zone 2' },
{ name: 'Shoreham', zone: 'DDY 4' },
{ name: 'Kooyong', zone: 'Zone 6' },
{ name: 'Kurrunjang', zone: 'Zone 3B' },
{ name: 'sorrento', zone: 'DDY 4' },
{ name: 'South Kinsville', zone: 'Zone 2' },
{ name: 'South Melbourne', zone: 'Zone 6' },
{ name: 'South Yarra', zone: 'Zone 6' },
{ name: 'Southbank', zone: 'Zone 9' },
{ name: 'Southland S/C', zone: 'DDY 6' },
{ name: 'Spotswood', zone: 'Zone 2' },
{ name: 'Springvale', zone: 'DDY 5' },
{ name: 'Springvale South', zone: 'DDY 5' },
{ name: 'St Albans', zone: 'Zone 1' },
{ name: 'St Andrews', zone: 'DDY 4' },
{ name: 'St Andrews Beach', zone: 'DDY 4' },
{ name: 'StKilda', zone: 'Zone 10' },
{ name: 'StKilda East', zone: 'Zone 10' },
{ name: 'StKilda RD', zone: 'Zone 10' },
{ name: 'StKilda West', zone: 'Zone 10' },
{ name: 'Strathmore', zone: 'Zone 5' },
{ name: 'Strathmore Heights', zone: 'Zone 5' },
{ name: 'Sunbury', zone: 'Zone 3B' },
{ name: 'Sunshine', zone: 'Zone 1' },
{ name: 'Sunshine North', zone: 'Zone 1' },
{ name: 'Sunshine West', zone: 'Zone 2' },
{ name: 'Surry Hills', zone: 'Zone 7' },
{ name: 'Sydenham', zone: 'Zone 3' },
{ name: 'Tarneit', zone: 'Zone 2' },
{ name: 'Taylors Hill', zone: 'Zone 3' },
{ name: 'Taylors Lakes', zone: 'Zone 3' },
{ name: 'Templestowe', zone: 'DDY 2' },
{ name: 'Templestowe Lower', zone: 'Zone 7' },
{ name: 'Thomastown', zone: 'Zone 4' },
{ name: 'Thornbury', zone: 'Zone 7' },
{ name: 'Toolern vale', zone: 'Zone 38' },
{ name: 'Toorak', zone: 'Zone 6' },
{ name: 'Mitcham', zone: 'DDY 2' },
{ name: 'Monash Uni Clayton', zone: 'DDY2' },
{ name: 'Mont Albert', zone: 'Zone 7' },
{ name: 'Tuerong', zone: 'DDY 4' },
{ name: 'Tullamrine', zone: 'Zone 8' },
{ name: 'Truganina', zone: 'Zone 1' },
{ name: 'Tyabb', zone: 'DDY 4' },
{ name: 'University of Melb', zone: 'Zone 8' },
{ name: 'Vermont', zone: 'DDY 2' },
{ name: 'Vermont South', zone: 'DDY 2' },
{ name: 'Viewbank', zone: 'Zone 5' },
{ name: 'Wantirna', zone: 'DDY 1' },
{ name: 'Wantirna South', zone: 'DDY 1' },
{ name: 'Warranwood', zone: 'DDY 1' },
{ name: 'Waterways', zone: 'DDY 5' },
{ name: 'Watsonia', zone: 'Zone 5' },
{ name: 'Watsonia North', zone: 'Zone 5' },
{ name: 'Werribee', zone: 'Zone 2' },
{ name: 'Werribee South', zone: 'Zone 2' },
{ name: 'West Footscray', zone: 'Zone 2' },
{ name: 'West Melbourne', zone: 'Zone 9' },
{ name: 'Westmeadows', zone: 'Zone 3' },
{ name: 'Wheelers Hill', zone: 'DDY 2' },
{ name: 'Williams RAAF', zone: 'Zone 2' },
{ name: 'Williamstown', zone: 'Zone 2' },
{ name: 'Williamstown North', zone: 'Zone 2' },
{ name: 'Windsor', zone: 'Zone 6' },
{ name: 'World Trade centre', zone: 'Zone 8' },
{ name: 'Wyndham Vale', zone: 'Zone 1' },
{ name: 'Yallambie', zone: 'Zone 5' },
{ name: 'Yarraville', zone: 'Zone 2' },
{ name: 'Yarraville West', zone: 'Zone 2' },
{ name: 'Manor Lakes', zone: 'Zone 1' },
{ name: 'Mambourin', zone: 'Zone 1' },
{ name: 'Parkdale', zone: 'DDY 6' },
{ name: 'Parwan', zone: 'Zone 3B' },
{ name: 'Parkville', zone: 'Zone 5' },
{ name: 'Pascoe Vale', zone: 'Zone 4' },
{ name: 'Pascoe Vale South', zone: 'Zone 4' },
{ name: 'Patterson Lakes', zone: 'DDY 6' },
{ name: 'Plumpton', zone: 'Zone 3' },
{ name: 'Point Cook', zone: 'Zone 1' },
{ name: 'Point Leo', zone: 'DDY 4' },
{ name: 'Portsea', zone: 'DDY 4' },
{ name: 'Aintree', zone: 'Zone 3' },
{ name: 'Deanside', zone: 'Zone 3' },
{ name: 'Fraser rise', zone: 'Zone 3' },
{ name: 'Keilor Lodge', zone: 'Zone 3' },
{ name: 'Rockbank', zone: 'Zone 3' },
{ name: 'EYNESBURY', zone: 'Tulla' },
{ name: 'GISBORNE SOUTH', zone: 'Zone 3B' },
{ name: 'HOPETOUN PARK', zone: 'Zone 3B' },
{ name: 'MOUNT COTTRELL', zone: 'Zone 3B' },
{ name: 'NEW GISBORNE', zone: 'Zone 3B' },
{ name: 'STRATHTULLOH', zone: 'Zone 3' },
{ name: 'Beveridge', zone: 'Tulla' },
{ name: 'Bolinda', zone: 'Tulla' },
{ name: 'Bylands', zone: 'Tulla' },
{ name: 'Cherokee', zone: 'Tulla' },
{ name: 'Donnybrook', zone: 'Tulla' },
{ name: 'EYNESBURY', zone: 'Tulla' },
{ name: 'Hanging Rock', zone: 'Tulla' },
{ name: 'Kalkallo', zone: 'Tulla' },
{ name: 'Kerrie', zone: 'Tulla' },
{ name: 'Kilmore', zone: 'Tulla' },
{ name: 'Kilmore East', zone: 'Tulla' },
{ name: 'Kyneton', zone: 'Tulla' },
{ name: 'Lancefield', zone: 'Tulla' },
{ name: 'Macedon', zone: 'Tulla' },
{ name: 'Skye', zone: 'DDY 4' },
{ name: 'Somers', zone: 'DDY 4' },
{ name: 'Somerton', zone: 'Zone 8' },
{ name: 'Somerville', zone: 'DDY 4' },
{ name: 'Tootgarook', zone: 'DDY 4' },
{ name: 'Tottenham', zone: 'Zone 1' },
{ name: 'Travencore', zone: 'Zone 9' },
{ name: 'Mickleham', zone: 'Tulla' },
{ name: 'Monegeetta', zone: 'Tulla' },
{ name: 'Mt Macedon', zone: 'Tulla' },
{ name: 'Riddels Creek', zone: 'Tulla' },
{ name: 'Ramsey', zone: 'Tulla' },
{ name: 'Wallan', zone: 'Tulla' },
{ name: 'Woodend', zone: 'Tulla' }






//     { name: 'ALBANVALE', zone: 'ZONE 1' },
//     { name: 'KURUNJANG', zone: 'ZONE 1' },
//     { name: 'ALBION', zone: 'ZONE 1' },
//     { name: 'LAVERTON NORTH', zone: 'ZONE 1' },
//     { name: 'ARDEER', zone: 'ZONE 1' },
//     { name: 'MELTON', zone: 'ZONE 1' },
//     { name: 'BRAYBROOK', zone: 'ZONE 1' },
//     { name: 'MELTON SOUTH', zone: 'ZONE 1' },
//     { name: 'BROOKFIELD', zone: 'ZONE 1' },
//     { name: 'MELTON WEST', zone: 'ZONE 1' },
//     { name: 'BURNSIDE', zone: 'ZONE 1' },
//     { name: 'RAVENHALL', zone: 'ZONE 1' },
//     { name: 'BURNSIDE HEIGHTS', zone: 'ZONE 1' },
//     { name: 'ST ALBANS', zone: 'ZONE 1' },
//     { name: 'CAIRNLEA', zone: 'ZONE 1' },
//     { name: 'SUNSHINE', zone: 'ZONE 1' },
//     { name: 'CAROLINE SPRINGS', zone: 'ZONE 1' },
//     { name: 'SUNSHINE NORTH', zone: 'ZONE 1' },
//     { name: 'COBBLEBANK', zone: 'ZONE 1' },
//     { name: 'SUNSHINE WEST', zone: 'ZONE 1' },
//     { name: 'DEER PARK', zone: 'ZONE 1' },
//     { name: 'TAYLORS HILL', zone: 'ZONE 1' },
//     { name: 'DERRIMUT', zone: 'ZONE 1' },
//     { name: 'TOTTENHAM', zone: 'ZONE 1' },
//     { name: 'GLENGALA', zone: 'ZONE 1' },
//     { name: 'TRUGANINA', zone: 'ZONE 1' },
//     { name: 'HARKNESS', zone: 'ZONE 1' },
//     { name: 'WEIR VIEWS', zone: 'ZONE 1' },
//     { name: 'KEALBA', zone: 'ZONE 1' },
//     { name: 'KEILOR', zone: 'ZONE 1' },
//     { name: 'ALTONA', zone: 'ZONE 2' },
//     { name: 'SEABROOK', zone: 'ZONE 2' },
//     { name: 'ALTONA MEADOWS', zone: 'ZONE 2' },
//     { name: 'SEAHOLME', zone: 'ZONE 2' },
//     { name: 'ALTONA NORTH', zone: 'ZONE 2' },
//     { name: 'SEDDON', zone: 'ZONE 2' },
//     { name: 'AVONDALE HEIGHTS', zone: 'ZONE 2' },
//     { name: 'SOUTH KINGSVILLE', zone: 'ZONE 2' },
//     { name: 'BROOKLYN', zone: 'ZONE 2' },
//     { name: 'SPOSTWOOD', zone: 'ZONE 2' },
//     { name: 'FOOTSCRAY', zone: 'ZONE 2' },
//     { name: 'TARNEIT', zone: 'ZONE 2' },
//     { name: 'FOOTSCRAY WEST', zone: 'ZONE 2' },
//     { name: 'WERRIBEE', zone: 'ZONE 2' },
//     { name: 'HIGHPOINT S/C', zone: 'ZONE 2' },
//     { name: 'WESTONA', zone: 'ZONE 2' },
//     { name: 'HOPPERS CROSSING', zone: 'ZONE 2' },
//     { name: 'WILLIAMS LANDING', zone: 'ZONE 2' },
//     { name: 'KEILOR EAST', zone: 'ZONE 2' },
//     { name: 'WILLIAMS RAAF', zone: 'ZONE 2' },
//     { name: 'KINGSVILLE', zone: 'ZONE 2' },
//     { name: 'WILLIAMSTOWN', zone: 'ZONE 2' },
//     { name: 'LAVERTON', zone: 'ZONE 2' },
//     { name: 'WILLIAMSTOWN NTH', zone: 'ZONE 2' },
//     { name: 'LAVERTON RAAF', zone: 'ZONE 2' },
//     { name: 'YARRAVILLE', zone: 'ZONE 2' },
//     { name: 'MAIDSTONE', zone: 'ZONE 2' },
//     { name: 'YARRAVILLE WEST', zone: 'ZONE 2' },
//     { name: 'MARIBYRNONG', zone: 'ZONE 2' },
//     { name: 'NEWPORT', zone: 'ZONE 2' },
//     { name: 'ANTREE', zone: 'ZONE 3' },
// { name: 'ATTWOOD', zone: 'ZONE 3' },
// { name: 'BONNIEBROOK', zone: 'ZONE 3' },
// { name: 'CALDER PARK', zone: 'ZONE 3' },
// { name: 'CRAIGIEBURN', zone: 'ZONE 3' },
// { name: 'DEANSIDE', zone: 'ZONE 3' },
// { name: 'DELAHEY', zone: 'ZONE 3' },
// { name: 'EYNESBURY', zone: 'ZONE 3' },
// { name: 'FRASER RISE', zone: 'ZONE 3' },
// { name: 'GREENVALE', zone: 'ZONE 3' },
// { name: 'HILLSIDE', zone: 'ZONE 3' },
// { name: 'KEILOR DOWNS', zone: 'ZONE 3' },
// { name: 'KEILOR LODGE', zone: 'ZONE 3' },
// { name: 'KEILOR NORTH', zone: 'ZONE 3' },
// { name: 'KINGS PARK', zone: 'ZONE 3' },
// { name: 'MAMBOURIN', zone: 'ZONE 3' },
// { name: 'MANOR LAKES', zone: 'ZONE 3' },
// { name: 'MEADOW HEIGHTS', zone: 'ZONE 3' },
// { name: 'PLUMPTON', zone: 'ZONE 3' },
// { name: 'ROCKBANK', zone: 'ZONE 3' },
// { name: 'ROXBURGH PARK', zone: 'ZONE 3' },
// { name: 'SYDENHAM', zone: 'ZONE 3' },
// { name: 'TAYLORS LAKES', zone: 'ZONE 3' },
// { name: 'THORNHILL PARK', zone: 'ZONE 3' },
// { name: 'WESTMEADOWS', zone: 'ZONE 3' },
// { name: 'WYNDHAM VALE', zone: 'ZONE 3' },
// { name: 'BACCHUS MARSH', zone: 'ZONE 3B' },
// { name: 'COIMADAI (part)', zone: 'ZONE 3B' },
// { name: 'DARLEY', zone: 'ZONE 3B' },
// { name: 'DIGGERS REST', zone: 'ZONE 3B' },
// { name: 'GISBORNE', zone: 'ZONE 3B' },
// { name: 'GISBORNE STH', zone: 'ZONE 3B' },
// { name: 'HOPETOUN PARK', zone: 'ZONE 3B' },
// { name: 'LONG FOREST', zone: 'ZONE 3B' },
// { name: 'MADDINGLEY', zone: 'ZONE 3B' },
// { name: 'MERRIMU', zone: 'ZONE 3B' },
// { name: 'MOUNT COTTRELL', zone: 'ZONE 3B' },
// { name: 'NEW GISBORNE', zone: 'ZONE 3B' },
// { name: 'PARWAN', zone: 'ZONE 3B' },
// { name: 'STRATHTULLOH', zone: 'ZONE 3B' },
// { name: 'SUNBURY', zone: 'ZONE 3B' },
// { name: 'TOOLERN VALE', zone: 'ZONE 3B' },
// { name: 'BUNDOORA', zone: 'ZONE 4' },
// { name: 'EPPING', zone: 'ZONE 4' },
// { name: 'KEON PARK', zone: 'ZONE 4' },
// { name: 'KINGSBURY', zone: 'ZONE 4' },
// { name: 'LALOR', zone: 'ZONE 4' },
// { name: 'LATROBE UNI', zone: 'ZONE 4' },
// { name: 'MILL PARK', zone: 'ZONE 4' },
// { name: 'PASCOE VALE', zone: 'ZONE 4' },
// { name: 'PASCOE VALE SOUTH', zone: 'ZONE 4' },
// { name: 'PRESTON', zone: 'ZONE 4' },
// { name: 'RESERVOIR', zone: 'ZONE 4' },
// { name: 'THOMASTOWN', zone: 'ZONE 4' },
// { name: 'ABERFELDIE', zone: 'ZONE 5' },
// { name: 'JACANA', zone: 'ZONE 5' },
// { name: 'AIRPORT WEST', zone: 'ZONE 5' },
// { name: 'LOWER PLENTY', zone: 'ZONE 5' },
// { name: 'BRIAR HILL', zone: 'ZONE 5' },
// { name: 'MACLEOD', zone: 'ZONE 5' },
// { name: 'BRUNSWICK ALL', zone: 'ZONE 5' },
// { name: 'MONTMORENCY', zone: 'ZONE 5' },
// { name: 'COBURG', zone: 'ZONE 5' },
// { name: 'MORELAND', zone: 'ZONE 5' },
// { name: 'COBURG NORTH', zone: 'ZONE 5' },
// { name: 'NIDDRIE', zone: 'ZONE 5' },
// { name: 'ELTHAM', zone: 'ZONE 5' },
// { name: 'OAK PARK', zone: 'ZONE 5' },
// { name: 'ELTHAM NORTH', zone: 'ZONE 5' },
// { name: 'PARKVILLE', zone: 'ZONE 5' },
// { name: 'ESSENDON', zone: 'ZONE 5' },
// { name: 'RESEARCH', zone: 'ZONE 5' },
// { name: 'FAWKNER', zone: 'ZONE 5' },
// { name: 'ROSANNA', zone: 'ZONE 5' },
// { name: 'FITZROY NORTH', zone: 'ZONE 5' },
// { name: 'ROYAL HOSPITAL', zone: 'ZONE 5' },
// { name: 'GLENROY', zone: 'ZONE 5' },
// { name: 'ST HELENA', zone: 'ZONE 5' },
// { name: 'GREENSBOROUGH', zone: 'ZONE 5' },
// { name: 'STRATHMORE', zone: 'ZONE 5' },
// { name: 'HADFIELD', zone: 'ZONE 5' },
// { name: 'VIEWBANK', zone: 'ZONE 5' },
// { name: 'HEIDELBERG', zone: 'ZONE 5' },
// { name: 'WATSONIA', zone: 'ZONE 5' },
// { name: 'HEIDELBERG WEST', zone: 'ZONE 5' },
// { name: 'YALLAMBIE', zone: 'ZONE 5' },
// { name: 'ABBOTSFORD', zone: 'ZONE 6' },
// { name: 'ARMADALE', zone: 'ZONE 6' },
// { name: 'CHADSTONE', zone: 'ZONE 6' },
// { name: 'CHADSTONE S/C', zone: 'ZONE 6' },
// { name: 'CLIFTON HILL', zone: 'ZONE 6' },
// { name: 'COLLINGWOOD', zone: 'ZONE 6' },
// { name: 'FITZROY', zone: 'ZONE 6' },
// { name: 'HAWKSBURN', zone: 'ZONE 6' },
// { name: 'KEW', zone: 'ZONE 6' },
// { name: 'KEW EAST', zone: 'ZONE 6' },
// { name: 'KOOYONG', zone: 'ZONE 6' },
// { name: 'MALVERN', zone: 'ZONE 6' },
// { name: 'MALVERN EAST', zone: 'ZONE 6' },
// { name: 'PRAHRAN', zone: 'ZONE 6' },
// { name: 'SOUTH MELBOURNE', zone: 'ZONE 6' },
// { name: 'SOUTH YARRA', zone: 'ZONE 6' },
// { name: 'TOORAK', zone: 'ZONE 6' },
// { name: 'WINDSOR', zone: 'ZONE 6' },
// { name: 'ALPHINGTON', zone: 'ZONE 7' },
// { name: 'AUBURN', zone: 'ZONE 7' },
// { name: 'BALWYN', zone: 'ZONE 7' },
// { name: 'BALWYN NORTH', zone: 'ZONE 7' },
// { name: 'BELLFIELD', zone: 'ZONE 7' },
// { name: 'BULLEEN', zone: 'ZONE 7' },
// { name: 'CAMBERWELL', zone: 'ZONE 7' },
// { name: 'CANTERBURY', zone: 'ZONE 7' },
// { name: 'DEEPDENE', zone: 'ZONE 7' },
// { name: 'EAGLEMONT', zone: 'ZONE 7' },
// { name: 'FAIRFIELD', zone: 'ZONE 7' },
// { name: 'GREYTHORN', zone: 'ZONE 7' },
// { name: 'HAWTHORN', zone: 'ZONE 7' },
// { name: 'HAWTHORN EAST', zone: 'ZONE 7' },
// { name: 'IVANHOE', zone: 'ZONE 7' },
// { name: 'IVANHOE EAST', zone: 'ZONE 7' },
// { name: 'MONT ALBERT', zone: 'ZONE 7' },
// { name: 'NORTHCOTE', zone: 'ZONE 7' },
// { name: 'SURREY HILLS', zone: 'ZONE 7' },
// { name: 'TEMPLESTOWE LOWER', zone: 'ZONE 7' },
// { name: 'ABBOTSFORD', zone: 'ZONE 8' },
// { name: 'BROADMEADOWS', zone: 'ZONE 8' },
// { name: 'CAMPBELLFIELD', zone: 'ZONE 8' },
// { name: 'CLIFTON HILL', zone: 'ZONE 8' },
// { name: 'COLLINGWOOD', zone: 'ZONE 8' },
// { name: 'DOCKLANDS', zone: 'ZONE 8' },
// { name: 'GLADSTONE PARK', zone: 'ZONE 8' },
// { name: 'GOWANBRAE', zone: 'ZONE 8' },
// { name: 'KEILOR PARK', zone: 'ZONE 8' },
// { name: 'MELBOURNE AIRPORT', zone: 'ZONE 8' },
// { name: 'MELBOURNE CD 3000', zone: 'ZONE 8' },
// { name: 'SOMERTON', zone: 'ZONE 8' },
// { name: 'TULLAMARINE', zone: 'ZONE 8' },
// { name: 'WORLD TRADE CENTRE', zone: 'ZONE 8' },
// { name: 'ALBERT PARK', zone: 'ZONE 9' },
// { name: 'KENSINGTON', zone: 'ZONE 9' },
// { name: 'ASCOT VALE', zone: 'ZONE 9' },
// { name: 'MIDDLE PARK', zone: 'ZONE 9' },
// { name: 'BURNLEY', zone: 'ZONE 9' },
// { name: 'MOONEE PONDS', zone: 'ZONE 9' },
// { name: 'CREMORNE', zone: 'ZONE 9' },
// { name: 'NORTH MELBOURNE', zone: 'ZONE 9' },
// { name: 'EAST MELBOURNE', zone: 'ZONE 9' },
// { name: 'PORT MELBOURNE', zone: 'ZONE 9' },
// { name: 'FISHERMANS BEND', zone: 'ZONE 9' },
// { name: 'RICHMOND', zone: 'ZONE 9' },
// { name: 'FLEMINGTON', zone: 'ZONE 9' },
// { name: 'SOUTHBANK', zone: 'ZONE 9' },
// { name: 'GARDEN CITY', zone: 'ZONE 9' },
// { name: 'TRAVANCORE', zone: 'ZONE 9' },
// { name: 'JOLIMONT', zone: 'ZONE 9' },
// { name: 'WEST MELBOURNE', zone: 'ZONE 9' },
// { name: 'BALACLAVA', zone: 'ZONE 10' },
// { name: 'HAMPTON EAST', zone: 'ZONE 10' },
// { name: 'BENTLEIGH', zone: 'ZONE 10' },
// { name: 'HIGHETT', zone: 'ZONE 10' },
// { name: 'BENTLEIGH EAST', zone: 'ZONE 10' },
// { name: 'MCKINNON', zone: 'ZONE 10' },
// { name: 'BRIGHTON', zone: 'ZONE 10' },
// { name: 'MELBOURNE 3004', zone: 'ZONE 10' },
// { name: 'BRIGHTON EAST', zone: 'ZONE 10' },
// { name: 'MOORABIN', zone: 'ZONE 10' },
// { name: 'CARNEGIE', zone: 'ZONE 10' },
// { name: 'MURRUMBEENA', zone: 'ZONE 10' },
// { name: 'CAULFIELD', zone: 'ZONE 10' },
// { name: 'ORMOND', zone: 'ZONE 10' },
// { name: 'CAULFIELD NORTH', zone: 'ZONE 10' },
// { name: 'SANDRINGHAM', zone: 'ZONE 10' },
// { name: 'CAULFIELD SOUTH', zone: 'ZONE 10' },
// { name: 'ST KILDA', zone: 'ZONE 10' },
// { name: 'ELSTERNWICK', zone: 'ZONE 10' },
// { name: 'ST KILDA EAST', zone: 'ZONE 10' },
// { name: 'GARDENVALE', zone: 'ZONE 10' },
// { name: 'ST KILDA RD', zone: 'ZONE 10' },
// { name: 'GLENHUNTLY', zone: 'ZONE 10' },
// { name: 'RIPPONLEA', zone: 'ZONE 10' },
// { name: 'HAMPTON', zone: 'ZONE 10' },
// { name: 'POINT COOK', zone: 'POINT COOK' },
// { name: 'POINT COOK RAAF', zone: 'POINT COOK' },
// { name: 'SANCTUARY LAKES', zone: 'POINT COOK' },
// { name: 'BAYSWATER', zone: 'DDY1' },
// { name: 'BAYSWATER NORTH', zone: 'DDY1' },
// { name: 'BORONIA', zone: 'DDY1' },
// { name: 'KILSYTH', zone: 'DDY1' },
// { name: 'CHIRNSIDE PARK', zone: 'DDY1' },
// { name: 'CROYDON', zone: 'DDY1' },
// { name: 'CROYDON HILLS', zone: 'DDY1' },
// { name: 'CROYDON NORTH', zone: 'DDY1' },
// { name: 'CROYDON SOUTH', zone: 'DDY1' },
// { name: 'MOOROOLBARK', zone: 'DDY1' },
// { name: 'MOUNTAIN GATE', zone: 'DDY1' },
// { name: 'DONVALE', zone: 'DDY1' },
// { name: 'EASTLAND S C', zone: 'DDY1' },
// { name: 'FERNTREE GULLY', zone: 'DDY1' },
// { name: 'HEATHMONT', zone: 'DDY1' },
// { name: 'KILSYTH SOUTH', zone: 'DDY1' },
// { name: 'KNOX CITY CENTRE', zone: 'DDY1' },
// { name: 'KNOXFIELD', zone: 'DDY1' },
// { name: 'LILYDALE', zone: 'DDY1' },
// { name: 'LYSTERFIELD', zone: 'DDY1' },
// { name: 'LYSTERFIELD SOUTH', zone: 'DDY1' },
// { name: 'MONTROSE', zone: 'DDY1' },
// { name: 'RINGWOOD', zone: 'DDY1' },
// { name: 'RINGWOOD EAST', zone: 'DDY1' },
// { name: 'RINGWOOD NORTH', zone: 'DDY1' },
// { name: 'ROWVILLE', zone: 'DDY1' },
// { name: 'SCORESBY', zone: 'DDY1' },
// { name: 'SCORESBY BC', zone: 'DDY1' },
// { name: 'WANTIRNA', zone: 'DDY1' },
// { name: 'WANTIRNA SOUTH', zone: 'DDY1' },
// { name: 'ASHWOOD', zone: 'DDY2' },
// { name: 'ASHBURTON', zone: 'DDY2' },
// { name: 'BLACKBURN', zone: 'DDY2' },
// { name: 'BLACKBURN NORTH', zone: 'DDY2' },
// { name: 'BLACKBURN SOUTH', zone: 'DDY2' },
// { name: 'BOX HILL', zone: 'DDY2' },
// { name: 'BOX HILL CENTRAL', zone: 'DDY2' },
// { name: 'BOX HILL NORTH', zone: 'DDY2' },
// { name: 'BOX HILL SOUTH', zone: 'DDY2' },
// { name: 'BURWOOD', zone: 'DDY2' },
// { name: 'BURWOOD EAST', zone: 'DDY2' },
// { name: 'BURWOOD HEIGHTS', zone: 'DDY2' },
// { name: 'DONCASTER EAST', zone: 'DDY2' },
// { name: 'DONCASTER', zone: 'DDY2' },
// { name: 'FOREST HILL', zone: 'DDY2' },
// { name: 'GLEN WAVERLEY', zone: 'DDY2' },
// { name: 'HARTWELL', zone: 'DDY2' },
// { name: 'LABURNUM', zone: 'DDY2' },
// { name: 'MALVERN EAST', zone: 'DDY2' },
// { name: 'MITCHAM', zone: 'DDY2' },
// { name: 'MITCHAM NORTH', zone: 'DDY2' },
// { name: 'MONT ALBERT NTH', zone: 'DDY2' },
// { name: 'MOUNT WAVERLEY', zone: 'DDY2' },
// { name: 'NUNAWADING', zone: 'DDY2' },
// { name: 'NUNAWADING BC', zone: 'DDY2' },
// { name: 'OAKLEIGH EAST', zone: 'DDY2' },
// { name: 'TARONGA', zone: 'DDY2' },
// { name: 'TEMPLESTOWE', zone: 'DDY2' },
// { name: 'VERMONT', zone: 'DDY2' },
// { name: 'VERMONT SOUTH', zone: 'DDY2' },
// { name: 'WHEELERS HILL', zone: 'DDY2' },
// { name: 'CRANBOURNE', zone: 'DDY3' },
// { name: 'DOVETON', zone: 'DDY3' },
// { name: 'CRANBOURNE EAST', zone: 'DDY3' },
// { name: 'ENDEAVOUR HILLS', zone: 'DDY3' },
// { name: 'CRANBOURNE NTH', zone: 'DDY3' },
// { name: 'EUMEMMERRING', zone: 'DDY3' },
// { name: 'CRANBOURNE STH', zone: 'DDY3' },
// { name: 'FOUNTAIN GATE', zone: 'DDY3' },
// { name: 'CRANBOURNE WST', zone: 'DDY3' },
// { name: 'HALLAM', zone: 'DDY3' },
// { name: 'BOTANIC RIDGE', zone: 'DDY3' },
// { name: 'NARRE WARREN', zone: 'DDY3' },
// { name: 'JUNCTION VILLAGE', zone: 'DDY3' },
// { name: 'LYNBROOK', zone: 'DDY3' },
// { name: 'NARRE WARREN SOUTH', zone: 'DDY3' },
// { name: 'NARRE WARREN NORTH', zone: 'DDY3' },
// { name: 'LYNDHURST', zone: 'DDY3' },
// { name: 'ARTHURS SEAT', zone: 'DDY4' },
// { name: 'BALNARRING', zone: 'DDY4' },
// { name: 'BALNARRING BEACH', zone: 'DDY4' },
// { name: 'BAXTER', zone: 'DDY4' },
// { name: 'BITTERN', zone: 'DDY4' },
// { name: 'BLAIRGOWRIE', zone: 'DDY4' },
// { name: 'BONEO', zone: 'DDY4' },
// { name: 'CAPE SCHANCK', zone: 'DDY4' },
// { name: 'CAPEL SOUND', zone: 'DDY4' },
// { name: 'CARRUM DOWNS', zone: 'DDY4' },
// { name: 'CRIB POINT', zone: 'DDY4' },
// { name: 'DEVON MEADOWS', zone: 'DDY4' },
// { name: 'DROMANA', zone: 'DDY4' },
// { name: 'FINGAL', zone: 'DDY4' },
// { name: 'FRANKSTON', zone: 'DDY4' },
// { name: 'FRANKSTON SOUTH', zone: 'DDY4' },
// { name: 'FRANKSTON NORTH', zone: 'DDY4' },
// { name: 'FLINDERS', zone: 'DDY4' },
// { name: 'HASTINGS', zone: 'DDY4' },
// { name: 'KARINGAL', zone: 'DDY4' },
// { name: 'LANGWARRIN', zone: 'DDY4' },
// { name: 'LANGWARRIN STH', zone: 'DDY4' },
// { name: 'MAIN RIDGE', zone: 'DDY4' },
// { name: 'MCCRAE', zone: 'DDY4' },
// { name: 'MERRICKS', zone: 'DDY4' },
// { name: 'MERRICKS NORTH', zone: 'DDY4' },
// { name: 'MOOROODUC', zone: 'DDY4' },
// { name: 'MORNINGTON', zone: 'DDY4' },
// { name: 'MOUNT MARTHA', zone: 'DDY4' },
// { name: 'MOUNT ELIZA', zone: 'DDY4' },
// { name: 'PEARCEDALE', zone: 'DDY4' },
// { name: 'POINT LEO', zone: 'DDY4' },
// { name: 'PORTSEA', zone: 'DDY4' },
// { name: 'RED HILL SOUTH', zone: 'DDY4' },
// { name: 'RED HILL', zone: 'DDY4' },
// { name: 'ROSEBUD', zone: 'DDY4' },
// { name: 'ROSEBUD PLAZA', zone: 'DDY4' },
// { name: 'ROSEBUD WEST', zone: 'DDY4' },
// { name: 'RYE', zone: 'DDY4' },
// { name: 'SANDHURST', zone: 'DDY4' },
// { name: 'SAFETY BEACH', zone: 'DDY4' },
// { name: 'SKYE', zone: 'DDY4' },
// { name: 'SHOREHAM', zone: 'DDY4' },
// { name: 'SOMERS', zone: 'DDY4' },
// { name: 'SOMERVILLE', zone: 'DDY4' },
// { name: 'SORRENTO', zone: 'DDY4' },
// { name: 'ST ANDREWS BEACH', zone: 'DDY4' },
// { name: 'TOOTGAROOK', zone: 'DDY4' },
// { name: 'TUERONG', zone: 'DDY4' },
// { name: 'TYABB', zone: 'DDY4' },
// { name: 'HMAS CEREBUS', zone: 'DDY4' },
// { name: 'BANGHOLME', zone: 'DDY5' },
// { name: 'BRAESIDE', zone: 'DDY5' },
// { name: 'BRANDON PARK', zone: 'DDY5' },
// { name: 'CLARINDA', zone: 'DDY5' },
// { name: 'CLAYTON', zone: 'DDY5' },
// { name: 'CLAYTON SOUTH', zone: 'DDY5' },
// { name: 'DANDENONG', zone: 'DDY5' },
// { name: 'DANDENONG EAST', zone: 'DDY5' },
// { name: 'DANDENONG NORTH', zone: 'DDY5' },
// { name: 'DANDENONG PLAZA', zone: 'DDY5' },
// { name: 'DANDENONG SOUTH', zone: 'DDY5' },
// { name: 'DINGLEY', zone: 'DDY5' },
// { name: 'DINGLEY VILLAGE', zone: 'DDY5' },
// { name: 'HEATHERTON', zone: 'DDY5' },
// { name: 'HUGHESDALE', zone: 'DDY5' },
// { name: 'HUNTINGDALE', zone: 'DDY5' },
// { name: 'KEYSBOROUGH', zone: 'DDY5' },
// { name: 'MOUNT WAVERLEY', zone: 'DDY5' },
// { name: 'MONASH UNIVERSITY', zone: 'DDY5' },
// { name: 'MULGRAVE', zone: 'DDY5' },
// { name: 'NOBLE PARK', zone: 'DDY5' },
// { name: 'NOBLE PARK EAST', zone: 'DDY5' },
// { name: 'NOBLE PARK NORTH', zone: 'DDY5' },
// { name: 'NOTTING HILL', zone: 'DDY5' },
// { name: 'OAKLEIGH', zone: 'DDY5' },
// { name: 'OAKLEIGH SOUTH', zone: 'DDY5' },
// { name: 'SPRINGVALE', zone: 'DDY5' },
// { name: 'SPRINGVALE SOUTH', zone: 'DDY5' },
// { name: 'WATERWAYS', zone: 'DDY5' },
// { name: 'ASPENDALE', zone: 'DDY6' },
// { name: 'ASPENDALE GARDENS', zone: 'DDY6' },
// { name: 'BEAUMARIS', zone: 'DDY6' },
// { name: 'BLACK ROCK', zone: 'DDY6' },
// { name: 'BONBEACH', zone: 'DDY6' },
// { name: 'CARRUM', zone: 'DDY6' },
// { name: 'CHELSEA', zone: 'DDY6' },
// { name: 'CHELSEA HEIGHTS', zone: 'DDY6' },
// { name: 'CHELTENHAM', zone: 'DDY6' },
// { name: 'CHELTENHAM EAST', zone: 'DDY6' },
// { name: 'EDITHVALE', zone: 'DDY6' },
// { name: 'MENTONE', zone: 'DDY6' },
// { name: 'MENTONE EAST', zone: 'DDY6' },
// { name: 'MOORABBIN AIRPORT', zone: 'DDY6' },
// { name: 'MORDIALLOC', zone: 'DDY6' },
// { name: 'MORDIALLOC NORTH', zone: 'DDY6' },
// { name: 'PARKDALE', zone: 'DDY6' },
// { name: 'PATTERSON LAKES', zone: 'DDY6' },
// { name: 'SEAFORD', zone: 'DDY6' },
// { name: 'SOUTHLAND SHOPPING', zone: 'DDY6' },
// { name: 'CENTRE', zone: 'DDY6' },
// { name: 'CHELTENHAM NORTH', zone: 'DDY6' },
// { name: 'BEACONSFIELD', zone: 'NARREWARREN DEPOT' },
// { name: 'BERWICK', zone: 'NARREWARREN DEPOT' },
// { name: 'HAMPTON PARK', zone: 'NARREWARREN DEPOT' },
// { name: 'OFFICER', zone: 'NARREWARREN DEPOT' },
// { name: 'PAKENHAM', zone: 'NARREWARREN DEPOT' },
// { name: 'PAKENHAM SOUTH', zone: 'NARREWARREN DEPOT' }

  ];
  filteredItems: any[] = [];
  suggestedItems: any[] = [];
  searchTerm = '';
  selected: any = null;
  showSuggestion = false;

  filterItems() {
    this.filteredItems = this.items.filter(item => item.name.toLowerCase().includes(this.searchTerm.toLowerCase()));
    this.selected = null;
    this.showSuggestion = false;
  }

  showSuggestions() {
    this.suggestedItems = this.items.filter(item => item.name.toLowerCase().startsWith(this.searchTerm.toLowerCase()));
    this.showSuggestion = this.suggestedItems.length > 0;
    this.selected = null;
  }

  selectSuggestion(suggestion: any) {
    this.searchTerm = suggestion.name;
    this.filterItems();
  }
/* Opens up searched result in a popup in google maps
  openGoogleMaps() {
    const suburb = this.searchTerm.trim().toLowerCase();
    const googleMapsUrl = `https://www.google.com/maps/place/${suburb}`;
    const popupWindow = window.open(googleMapsUrl, 'Google Maps', 'width=800,height=600');
    if (popupWindow) {
      popupWindow.focus();
    }
  }
*/
}
